spring:
  datasource:
    url: jdbc:mysql://localhost:3306/review_community_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Vinay@321
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
server:
  port: 9192

jwt:
  secret: vinay
  expiration: 36000000