spring:
  datasource:
    url: //your-database-instance-url
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: //your-database-username
    password: //your-database-user-password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
server:
  port: //port

jwt:
  secret: //jwt-secret
  expiration: //jwt-token-expiration-time